/* Generated By:JavaCC: Do not edit this line. MitabLineParserConstants.java */
package psidev.psi.mi.jami.tab.io.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MitabLineParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RANGE_SEPARATOR = 3;
  /** RegularExpression Id. */
  int PUB_DATE = 4;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int STOICHIOMETRY = 6;
  /** RegularExpression Id. */
  int COMMENT = 7;
  /** RegularExpression Id. */
  int FIELD_SEPARATOR = 8;
  /** RegularExpression Id. */
  int COLUMN_SEPARATOR = 9;
  /** RegularExpression Id. */
  int LINE_SEPARATOR = 10;
  /** RegularExpression Id. */
  int OPEN_PAREN = 11;
  /** RegularExpression Id. */
  int CLOSE_PAREN = 12;
  /** RegularExpression Id. */
  int COLON = 13;
  /** RegularExpression Id. */
  int DASH = 14;
  /** RegularExpression Id. */
  int LESSTHAN = 15;
  /** RegularExpression Id. */
  int GREATERTHAN = 16;
  /** RegularExpression Id. */
  int POSITION = 17;
  /** RegularExpression Id. */
  int TAXID = 18;
  /** RegularExpression Id. */
  int NEGATIVE = 19;
  /** RegularExpression Id. */
  int QUOTED_STRING = 20;
  /** RegularExpression Id. */
  int ANY_CHAR = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\f\"",
    "\",\"",
    "<PUB_DATE>",
    "<NUMBER>",
    "<STOICHIOMETRY>",
    "\"#\"",
    "\"|\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\"-\"",
    "\"<\"",
    "\">\"",
    "<POSITION>",
    "\"taxid\"",
    "<NEGATIVE>",
    "<QUOTED_STRING>",
    "<ANY_CHAR>",
    "\"..\"",
  };

}
